### ISSUE TITLE
User Profile not editable when user is logged in using query parameters

### ISSUE THREAD

**Issue by mhamendes** [Stand-With-Crypto/swc-web#1320]
When the user is logged in using `sessionId` and `userId` query parameters, the profile page still shows the unauthenticated component for the EditProfile component.

**Comment by twistershark** [comment]
This would change our current rules for this. 

https://github.com/Stand-With-Crypto/swc-web/blob/5eb2b7591ed9562fe75136c71aa2219fe5140a55/src/components/app/pageUserProfile/index.tsx#L92

To change the behaviour, the change here would be to just remove the `useThirdwebSession` param and the `LoginDialogWrapper` component would verify that the user is logged in. 

@travisbloom-cb Can we have your opinion on this?

**Comment by twistershark** [comment]
I did some testing and I think that we prob won't want to change the current behavior because of the following scenario:

- If a user visits SWC from a email link, we will sign in the user but no wallet will be associated with that login. If the user completes any action that has a NFT reward at the end while in this "partial" sign in state, the user won't really receive any NFTs _(even though our success screen says that the user received a NFT. @travisbloom-cb Maybe we should check this to prevent misinformation)_

- The user needs to go to profile page and click on "Claim my NFTs" to login with a thirdweb session before we show the Update profile button. Maybe we could just add a different button for "Claim my NFTs" and leave "update profile" without this thirdweb session restriction. 

_(I'm not sure what happens if the user never log in using a wallet. If I'm not mistaken, we will wait until the user connects a wallet to send all pending NFTs, but not 100% sure yet)_

**Comment by twistershark** [comment]
Closed by https://github.com/Stand-With-Crypto/swc-web/pull/1360
