### ISSUE TITLE
Upgrade Packages

### ISSUE THREAD

**Issue by twistershark** [Stand-With-Crypto/swc-web#1350]
We have a lot of outdated packages and as we want to migrate to NextJS v15 as soon as possible, updating the packages can help reduce the amount of conflicts to resolve later.

This is the current list of outdated packages(`npm outdated`):
<img width="869" alt="image" src="https://github.com/user-attachments/assets/ad32a252-e582-4d9d-aca2-890c42ca3653">

**Comment by olavoparno** [comment]
Upon upgrading react to ^19.0.0-rc-a99d8e8d-20240916 and next to ^15.0.0-rc.0 and some other deps around them, turbo still crashes on the development environment. Followed https://nextjs.org/docs/app/building-your-application/upgrading/version-15

Also, there's still no support for some wrappers on our next.config, Sentry is one of them https://github.com/getsentry/sentry-javascript/issues/8105 but still even without Sentry and BundleAnalyzer's wrappers, Turbopack warning resolves but still crashes on the development environment. 

Upon upgrading all dependencies indiscriminately, ethers broke prob due to the way it is bundled on their side.
