### ISSUE TITLE
Verify data science updates to dashboards and tooling using v2 information

### ISSUE THREAD

**Issue by travisbloom-cb** [Stand-With-Crypto/swc-web#160]

**Comment by benson-budiman-cb** [comment]
2024-03-11 update: waiting on data engineers to post updates on the data migration

**Comment by benson-budiman-cb** [comment]
2024-03-13 update: https://coinbase.slack.com/archives/C05TC4XDG0M/p1710351463256399?thread_ts=1709766573.845219&cid=C05TC4XDG0M

Situation summary:

- We actually do have plenty of duplicate users with the same emails/crypto addresses in the SWC database from the initial backfill script. However, those users should be merged once they log into SWC for the first time.
- There are some cases where a merge won't happen though - for example, if the backfill only included a user's email address (so we do not have their crypto address), but the same user logs into SWC V2 with a crypto address, then a merge won't happen because we cannot associate the new login with existing information. This is **_intentional_**.
- On that same note, if a user signs into SWC with a crypto address, and then that same user signs into SWC with an email address, that will actually create two different users in our SWC database. This is **_intentional_**.

At most, we should proactively merge the first set of users.

**Comment by benson-budiman-cb** [comment]
2024-03-22 update:

- I have a [PR](https://github.com/Stand-With-Crypto/swc-web/pull/674) open that will merge the duplicate backfilled users that have not logged-in.
- I want to test that PR in a Vercel environment to ensure we don't run into issues regarding timeouts, serverless functions, etc., but I am blocked because of [this issue](https://github.com/Stand-With-Crypto/swc-web/issues/660).

**Comment by travisbloom-cb** [comment]
@benson-budiman-cb can this be closed?
