### ISSUE TITLE
Dont crash when user has cookies blocked on safari

### ISSUE THREAD

**Issue by travisbloom-cb** [Stand-With-Crypto/swc-web#733]
[This sentry error](https://stand-with-crypto.sentry.io/issues/5028531279/?environment=production&project=4506490717470720&query=&referrer=issue-stream&statsPeriod=14d&stream_index=2) occurs when a user visits the site on safari with cookies blocked.

Steps to reproduce:
- set "Safari Settings -> Advanced -> Block all cookies"
- load swc in safari

We already [try catch our calls to localstorage](https://github.com/Stand-With-Crypto/swc-web/blob/638-location-specific-pages/src/utils/web/localStorage.ts#L12) for this exact reason, but it looks like some third party libraries like "WalletConnect" call localstorage directly and crash the site.

I think the fix here is we inline a script tag at the top of our app before anything else loads that overrides the global localStorage function with a version that wraps all the calls in try catch. Ugly hack 🤷

**Comment by benson-budiman-cb** [comment]
_2024-04-01-02:38pm UPDATE:_ 

I've tried to overwrite the local storage _functions_ via the [PR](https://github.com/Stand-With-Crypto/swc-web/pull/735) above, but that does not fix the issue - the thing is, _any access to the local storage (even something like `console.log(localStorage)` causes the insecure error, so overwriting the functions does not matter.

If there is an answer to this, then it would involve somehow checking if the browser can access the local storage, but this check would have to be built part of the local storage because it needs to essentially intercept any calls to `localStorage`. Most solutions out there involve a wrapper function/wrapper around the local storage to do this, but we can't do that given that it's a third-party package that is hitting the local storage directly.
