### ISSUE TITLE
orchestrate e2e test coverage reporting for cypress

### ISSUE THREAD

**Issue by travisbloom-cb** [Stand-With-Crypto/swc-web#795]
See [these docs](https://docs.cypress.io/guides/tooling/code-coverage).

We have a paid cypress.io account so if there's any best practices for integrating our coverage with that suite we'll want to leverage.

**Comment by eduardopicolo-cb** [comment]
Currently there's no way to [instrument the code](https://nextjs.org/docs/architecture/nextjs-compiler), as NextJS uses a [custom transpiler](https://nextjs.org/docs/architecture/nextjs-compiler) which is incompatible with existing plugins.

Downgrading to Babel is not an option because most of the cutting-edge Nextjs features will stop working, like the App Router and Font Optimization:
![image](https://github.com/Stand-With-Crypto/swc-web/assets/167582510/bfe40050-2bb1-4928-a3e8-6498d8e489d8)

---
### Potential Solution to keep an eye on:

There is an [open source plugin](https://github.com/kwonoj/swc-plugin-coverage-instrument) that works with SWC transpiler, but unfortunatelly it does not work with App Router:
![image](https://github.com/Stand-With-Crypto/swc-web/assets/167582510/5d4d2187-dd56-4bb5-a82b-d4ffebf9f8c4)


Some issues to keep an eye on:
https://github.com/vercel/next.js/discussions/53901
https://github.com/istanbuljs/babel-plugin-istanbul/issues/285

**Comment by lucasrmp-cb** [comment]
Technically impossible on the current version of nextjs we use
