### ISSUE TITLE
Ensure we update the advocate's address if needed in capital canary before sending an email to their rep

### ISSUE THREAD

**Issue by travisbloom-cb** [Stand-With-Crypto/swc-web#898]
In [this fn](https://github.com/Stand-With-Crypto/swc-web/blob/main/src/inngest/functions/capitolCanary/emailRepViaCapitolCanary.ts#L30), we need to ensure that we update the address of the advocate in capital canary, before sending the email. Otherwise we might get errors from CC because we tried to email using a legacy incomplete address. I believe this will drastically reduce the incidences we see of [this error](https://stand-with-crypto.sentry.io/issues/5119099756/?environment=production&project=4506490717470720&query=is%3Aunresolved+timesSeen%3A%3E%3D10&referrer=issue-stream&statsPeriod=30d&stream_index=1)

**Comment by lucasrmp-cb** [comment]
Closing this since upon debugging I found out that for every email request we do a full upsert of the user that already updates the address before sending the email request, see below for more context
[https://github.com/Stand-With-Crypto/swc-web/blob/e516ebb28b35cddb9efaebc43dace89b[…]src/inngest/functions/capitolCanary/emailRepViaCapitolCanary.ts](https://github.com/Stand-With-Crypto/swc-web/blob/e516ebb28b35cddb9efaebc43dace89babd3244d/src/inngest/functions/capitolCanary/emailRepViaCapitolCanary.ts#L75-L76)

**Comment by lucasrmp-cb** [comment]
Closing this since upon debugging I found out that for every email request we do a full upsert of the user that already updates the address before sending the email request, see below for more context
[https://github.com/Stand-With-Crypto/swc-web/blob/e516ebb28b35cddb9efaebc43dace89b[…]src/inngest/functions/capitolCanary/emailRepViaCapitolCanary.ts](https://github.com/Stand-With-Crypto/swc-web/blob/e516ebb28b35cddb9efaebc43dace89babd3244d/src/inngest/functions/capitolCanary/emailRepViaCapitolCanary.ts#L75-L76)
