### ISSUE TITLE
Audit our usage of Google Civic API to minimize per-user queries

### ISSUE THREAD

**Issue by travisbloom-cb** [Stand-With-Crypto/swc-web#899]
We currently use the [civic api](https://github.com/Stand-With-Crypto/swc-web/blob/main/src/utils/shared/googleCivicInfo.ts#L129) to match users addresses with their congressional district. Given the [quota constraints of the API](https://coinbase.slack.com/archives/C074HPDK067/p1716382288361219), we should audit all the places we use it and see if there's any unnecessary queries/things that can be optimized. 

Example questions:
- are we fetching from the API when users have an incomplete address/no address populated?
- Are we fetching from the API every time a user loads /politicians or one of the /race pages if they have an address? Can we cache this result so we dont need to fetch every time?

**Comment by matheusmendes-cb** [comment]
Actually, after a further investigation that is not the case. The [requests are not started](https://swr.vercel.app/docs/conditional-fetching) because we set `useSWR` key to `null` if `address` is empty. In this case, our code is safe and we are not making unnecessary requests in case we do not have an address.

We make those requests in these hooks:
- [useGetDTSIPeopleFromAddress](https://github.com/Stand-With-Crypto/swc-web/blob/e5240373aea38da8e0734efa4823a4e226339c84/src/hooks/useGetDTSIPeopleFromAddress.ts#L71-L78)
- [useGetDistrictFromAddress](https://github.com/Stand-With-Crypto/swc-web/blob/e5240373aea38da8e0734efa4823a4e226339c84/src/hooks/useGetDistrictFromAddress.ts#L8-L16)
